### ISSUE TITLE
Should only approve node server CSRs (not client/other CSR)

### ISSUE THREAD

**Issue by sjenning** [openshift/cluster-machine-approver#6]

**Comment by mrogers950** [comment]
Do we want to follow the same node approval process (or some variant of) from https://github.com/coreos/kubecsr/blob/master/Documentation/kube-aws-approver.md ?

**Comment by sjenning** [comment]
Yes, that is a great starting place :+1:  Of course, we can make it platform agnostic using the machine-api.
